# Tensor Manipulation

## Imports

In [1]:
import torch

## 2D Array with PyTorch

In [2]:
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


`.dim()` 메소드는 해당 변수의 차원을 구해준다. 예를 들어 벡터(선)은 1차원, 행렬(면)은 2차원, 텐서(도형)은 3차원의 값을 가지게 된다.

In [3]:
print(t.dim())
print(t.size()) # shape
print(t[:, 1]) # 2번째 열, 즉 2번째 열벡터의 원소
print(t[:, 1].size())

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [4]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [5]:
print(t.dim())
print(t.size())

4
torch.Size([1, 2, 3, 4])


## 차원 변경하기

### Squeeze

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape: ($A \times 1 \times B \times C \times 1 \times D$) then the out tensor will be of shape: ($A \times B \times C \times D$).

When dim is given, a squeeze operation is done only in the given dimension. If input is of shape: ($A \times 1 \times B$), `squeeze(input, 0)` leaves the tensor unchanged, but `squeeze(input, 1)` will squeeze the tensor to the shape ($A \times B$)

In [7]:
x = torch.FloatTensor([[0], [1], [2]])
print(x)
print(x.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(x.squeeze())
print(x.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


차원이 1인 값이 없으면 아무것도 변하지 않는다.

In [10]:
x = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]])
print(x.squeeze())
print(x.squeeze().shape)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


### Unsqueeze

Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.


In [15]:
x = torch.tensor([1, 2, 3, 4])
print(x.shape)

torch.Size([4])


In [16]:
print(x.unsqueeze(0))
print(x.unsqueeze(0).size())
print(x.unsqueeze(1))
print(x.unsqueeze(1).size())

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


`view()` 메소드로도 같은 작업을 할 수 있다.

In [18]:
print(x.view(1, -1))
print(x.view(1,-1).shape)
print(x.view(-1,1))
print(x.view(-1,1).shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


## One-hot encoding

In [20]:
x = torch.LongTensor([[0], [1], [2], [3], [0]])
print(x)

tensor([[0],
        [1],
        [2],
        [3],
        [0]])


In [24]:
one_hot = torch.zeros(5,4) # batch_size = 5, classes = 4
one_hot.scatter_(1, x, 1)
print(one_hot)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]])
